### ISSUE TITLE
Не работает кнопка Apply

### ISSUE THREAD

**Issue by DimaKovalchuk** [Jojorr/ChatApp#11]
Шаги по воспроизведению проблемы:
1. Запустил программу.
2.Ввел Local nick
3. Нажал Apply

Ожидаемый результат:
Выводится приветствие:
“ChatApp 2015 user ник ­юзера­ на­ сервере”

Фактический результат:
Ничего не выводится.

**Comment by Jojorr** [comment]
Собственно приветствие:
“ChatApp 2015 user ник ­юзера­ на­ сервере” должно выводиться при подключении к пользователю, а Apply всего лишь меняет ник и выводит сообщение такого формата: "[System] Nickname changed to: ник юзера на сервере"
