### ISSUE TITLE
Сообщения не отправляются.

### ISSUE THREAD

**Issue by DimaKovalchuk** [Jojorr/ChatApp#12]
Шаги по воспроизведению проблемы:
1. Запустить программу.
2. Подключиться к собеседнику
3. Набрал сообщение
4.Нажал кнопку Send

Ожидаемый результат:
Корректное отправление сообщений

Фактический результат:
Сообщение не отправлено.

**Comment by Shazex** [comment]
Проблема не на нашей стороне, программа тестилась и сдавалась, все нормально работает
