### ISSUE TITLE
Вывод в текстовой области пустых сообщений.

### ISSUE THREAD

**Issue by ikurc** [Jojorr/ChatApp#13]
Шаги по воспроизведению проблемы:
1. Запустить один экземпляр ChatApp.
2. Ввести ник пользователя, нажать Apply.
3. В строке ввода сообщения ничего не писать, оставить пустым.
4. Send.

Ожидаемый результат:
Игнорирование сообщения с количеством символов меньше одного.

Фактический результат:
Вывод в текстовой области пустых сообщений от имени пользователя.
![default](https://cloud.githubusercontent.com/assets/15365823/11917749/91885364-a71d-11e5-8a9f-3ce1cc4c3b43.JPG)

**Comment by Jojorr** [comment]
Не баг, а фича. Даем юзеру больше свободы)
