### ISSUE TITLE
Баг при добавлении друга

### ISSUE THREAD

**Issue by archy322** [Jojorr/ChatApp#14]
Шаги к воспроизведению проблемы:
1. Запустить чат.
2. Заполнить поля ник, адреса, и ник собеседника.
3. Нажать на кнопку "Add".
Ожидаемый результат:
В списке друзей отобразится ник собеседника, который мы ввели.
Фактический результат:
В списке друзей отображается "newfr", даже если ник собеседника не заполнен.
![default](https://cloud.githubusercontent.com/assets/15378242/11933115/77c1842e-a802-11e5-8e71-038d1cbbc7f2.png)

**Comment by Jojorr** [comment]
Данный функционал, не был реализован в чате, а всего лишь был добавлен элемент GUI
