### ISSUE TITLE
Баг при отправлении сообщений

### ISSUE THREAD

**Issue by archy322** [Jojorr/ChatApp#15]
Шаги к воспроизведению проблемы:
1. Запустить чат.
2. Заполнить поля ника и адреса.
3. Подключиться.
4. Нажать на кнопку "Send".
Ожидаемый результат:
Сообщение об ошибке отправки в связи с отсутствием текста.
Фактический результат:
Отправляется пустое сообщение.

**Comment by Jojorr** [comment]
Про этот баг нам уже сообщали, не актуально
