### ISSUE TITLE
Не поддерживает русские в сообщениях.

### ISSUE THREAD

**Issue by ElenVM** [Jojorr/ChatApp#2]
Шаги по воспроизведению проблемы:
1. Запустить программу.
2. Зарегестрироваться.
3. Ввести сообщение и отправить.

Ожидаемый результат:
Вывод сообщения русскими буквами.

Фактический результат:
Отправка идет русскими, так и считывает программа, но выводит пустые квадратики.

**Comment by Jojorr** [comment]
Исправлено
