### ISSUE TITLE
Удалить собеседника.

### ISSUE THREAD

**Issue by ElenVM** [Jojorr/ChatApp#3]
Шаги по воспроизведению проблемы:
1. Запустить программу.
2. Выбрать любой ник. Нажать Remove.
3. Перезапустить программу.

Ожидаемый результат:
В поле с контактами должен исчезнуть выбранный ранее ник.

Фактический результат:
Ник остается.

**Comment by Shazex** [comment]
Работа с сервером не реализована, поэтому этот баг не актуален
