### ISSUE TITLE
Добавить собеседника.

### ISSUE THREAD

**Issue by ElenVM** [Jojorr/ChatApp#4]
Шаги по воспроизведению проблемы:
1. Запустить программу.
2. Ввести локальный ник кириллицей. Нажать Add.
3. Перезапустить программу.

Ожидаемый результат:
В поле с контактами должен появиться введенный ранее ник.

Фактический результат:
Собеседник не появился в поле с контактами..

**Comment by Shazex** [comment]
Работа с сервером не реализована, поэтому этот баг не актуален
