### ISSUE TITLE
Исчезают кнопки

### ISSUE THREAD

**Issue by ElenVM** [Jojorr/ChatApp#5]
Шаги по воспроизведению проблемы:
1. Запустить программу.
2. Нажать кнопку Add, несколько раз. (Видимо у автора уже записан человек который автоматически добавляется при нажатии этой кнопки Add) 
3. Нажимать до тех пор, пока не заполнит полностью до конца окно.

Ожидаемый результат:
Либо пользователей можно перелистывать, либо поставить ограничение на количество.

Фактический результат:
Кнопки Send, Add, Remove, Connect исчезли.

**Comment by Shazex** [comment]
Работа с сервером не реализована, поэтому баг не актуален
