### ISSUE TITLE
Disconect не работает

### ISSUE THREAD

**Issue by mgarna** [Jojorr/ChatApp#6]
Шаги по воспроизведению проблемы:
1. Запустить ChatApp.
2. Ввести ник.
3.Ввести ip 
4. Connect
5. Общаемся
5.Disconect .

Ожидаемый результат:
Прекращение возможности отправлять сообщения
Фактический результат:
Возможность дальше общаться

**Comment by Shazex** [comment]
Проблема известна, исправим

**Comment by Shazex** [comment]
Исправлено
